export const BRANDS = {
  pertamina: { name: 'Pertamina', color: '#e8352a', short: 'PTM' },
  shell:     { name: 'Shell',     color: '#f5a524', short: 'SHL' },
  bp:        { name: 'BP',        color: '#4ca845', short: 'BP'  },
  vivo:      { name: 'Vivo',      color: '#1e90d7', short: 'VV'  },
};

export const FUELS = {
  pertalite:      { name: 'Pertalite',        ron: 'RON 90',  price: 10000 },
  pertamax:       { name: 'Pertamax',         ron: 'RON 92',  price: 12950 },
  pertamax_turbo: { name: 'Pertamax Turbo',   ron: 'RON 98',  price: 14000 },
  solar:          { name: 'Bio Solar',        ron: 'CN 48',   price: 6800  },
  dexlite:        { name: 'Dexlite',          ron: 'CN 51',   price: 14800 },
  shell_super:    { name: 'Shell Super',      ron: 'RON 92',  price: 13100 },
  shell_vpower:   { name: 'V-Power',          ron: 'RON 95',  price: 14100 },
  shell_diesel:   { name: 'Shell Diesel',     ron: 'CN 51',   price: 14500 },
  bp_90:          { name: 'BP 90',            ron: 'RON 90',  price: 10000 },
  bp_92:          { name: 'BP Ultimate 92',   ron: 'RON 92',  price: 13050 },
  bp_95:          { name: 'BP Ultimate 95',   ron: 'RON 95',  price: 14050 },
  bp_diesel:      { name: 'BP Diesel',        ron: 'CN 51',   price: 14200 },
  vivo_89:        { name: 'Revvo 89',         ron: 'RON 89',  price: 9500  },
  vivo_92:        { name: 'Revvo 92',         ron: 'RON 92',  price: 12900 },
  vivo_95:        { name: 'Revvo 95',         ron: 'RON 95',  price: 13900 },
  vivo_diesel:    { name: 'Vivo Diesel',      ron: 'CN 51',   price: 14000 },
  ev:             { name: 'EV Charging',      ron: '—',       price: 0     },
};

export const AMENITY_LABELS = {
  atm:            { id: 'ATM',          en: 'ATM'          },
  toilet:         { id: 'Toilet',       en: 'Restroom'     },
  mart:           { id: 'Minimarket',   en: 'Mini-mart'    },
  prayer:         { id: 'Mushola',      en: 'Prayer room'  },
  cafe:           { id: 'Kafe',         en: 'Café'         },
  wash:           { id: 'Cuci Mobil',   en: 'Car wash'     },
  ev:             { id: 'Pengisian EV', en: 'EV charging'  },
  compressed_air: { id: 'Angin Ban',    en: 'Air pump'     },
};

export const I18N = {
  id: {
    search: 'Cari SPBU, area, atau jalan…',
    filters: 'Filter',
    brand: 'Merek',
    fuel: 'Jenis bahan bakar',
    all: 'Semua',
    open_now: 'Buka sekarang',
    nearby: 'Terdekat',
    stations: 'SPBU',
    results: 'hasil',
    directions: 'Petunjuk arah',
    details: 'Detail',
    share: 'Bagikan',
    save: 'Simpan',
    saved: 'Tersimpan',
    queue_low: 'Sepi',
    queue_medium: 'Sedang',
    queue_high: 'Ramai',
    open: 'Buka',
    closed: 'Tutup',
    distance_from_you: 'dari lokasi Anda',
    price_per_liter: 'per liter',
    fuel_available: 'Bahan bakar tersedia',
    amenities: 'Fasilitas',
    reviews: 'ulasan',
    hours: 'Jam operasi',
    updated: 'Diperbarui',
    minutes_ago: 'menit yang lalu',
    brands_all: 'Semua merek',
    call: 'Telepon',
    no_results: 'Tidak ada SPBU ditemukan',
    no_results_sub: 'Coba ubah filter atau perluas pencarian',
    tweaks: 'Tweaks',
    theme: 'Tema',
    sidebar_side: 'Posisi panel',
    map_style: 'Gaya peta',
    light: 'Terang',
    dark: 'Gelap',
    left: 'Kiri',
    right: 'Kanan',
    standard: 'Standar',
    satellite: 'Satelit',
    minimal: 'Minimal',
    you: 'Anda',
    west_java: 'Jawa Barat',
    list: 'Daftar',
    map: 'Peta',
    sort_distance: 'Terdekat',
    sort_price: 'Termurah',
    sort_rating: 'Rating',
    routing_start: 'Dari lokasi Anda',
    routing_end: 'ke SPBU ini',
    routing_loading: 'Menghitung rute…',
    routing_error: 'Rute tidak ditemukan',
    routing_distance: 'Jarak',
    routing_duration: 'Estimasi',
    no_location: 'Lokasi tidak tersedia',
  },
  en: {
    search: 'Search stations, areas, or streets…',
    filters: 'Filters',
    brand: 'Brand',
    fuel: 'Fuel type',
    all: 'All',
    open_now: 'Open now',
    nearby: 'Nearby',
    stations: 'stations',
    results: 'results',
    directions: 'Get directions',
    details: 'Details',
    share: 'Share',
    save: 'Save',
    saved: 'Saved',
    queue_low: 'Quiet',
    queue_medium: 'Moderate',
    queue_high: 'Busy',
    open: 'Open',
    closed: 'Closed',
    distance_from_you: 'from you',
    price_per_liter: 'per liter',
    fuel_available: 'Fuels available',
    amenities: 'Amenities',
    reviews: 'reviews',
    hours: 'Hours',
    updated: 'Updated',
    minutes_ago: 'minutes ago',
    brands_all: 'All brands',
    call: 'Call',
    no_results: 'No stations found',
    no_results_sub: 'Try changing filters or expanding your search',
    tweaks: 'Tweaks',
    theme: 'Theme',
    sidebar_side: 'Panel side',
    map_style: 'Map style',
    light: 'Light',
    dark: 'Dark',
    left: 'Left',
    right: 'Right',
    standard: 'Standard',
    satellite: 'Satellite',
    minimal: 'Minimal',
    you: 'You',
    west_java: 'West Java',
    list: 'List',
    map: 'Map',
    sort_distance: 'Nearest',
    sort_price: 'Cheapest',
    sort_rating: 'Top rated',
    routing_start: 'From your location',
    routing_end: 'to this station',
    routing_loading: 'Calculating route…',
    routing_error: 'Route not found',
    routing_distance: 'Distance',
    routing_duration: 'Est. time',
    no_location: 'Location unavailable',
  },
};
